// Build-time SEO prerender — the reason circuitcenter.ai serves indexable HTML.
//
// The site is a client-rendered SPA behind nginx with no Node in the request
// path, so every URL used to resolve to one byte-identical index.html: same
// <title>, same meta description, no canonical, no JSON-LD. This step writes
// ONE static HTML file per templated route, each carrying that route's own head
// (built by @public/services/seo, the same module <PageHead> renders from) plus
// a <noscript> body for crawlers that do not execute JS. nginx then serves them
// with the try_files rule already in frontend/nginx.conf — no runtime cost, no
// extra request-path service, and not one byte added to the JS bundle.
//
// Scope is every templated route: home, the static pages, EVERY category and
// subcategory, and a CAPPED slice of part pages.
//
// Parts were excluded in the first pass on the assumption that prerendering
// them would be expensive. It is not: renderRoute is regex replacement over the
// built shell, not React SSR, so each document costs a few string operations
// and one file write. That is why parts are here at all — they are ~97% of the
// sitemap, so excluding them left the overwhelming majority of the site on the
// generic shell, and part-number searches are the long tail a components
// directory actually wins.
//
// Cheap per document is not free in aggregate, though. Each part page is a
// ~13 KB file, so the catalog's 270k+ parts would be a multi-GB dist/ — past
// what the frontend image, the deploy and the t3.small disk can carry. The
// manifest therefore ships a RANKED slice (see gen-seo-manifest.mjs): parts
// with a photo AND a price first, then stock descending, then newest. Parts
// outside it serve the SPA shell and get their head tags from helmet after
// hydration, which is already what every part added since the last regen does.
// The sitemap advertises exactly this same slice: /api/sitemap-parts-{n}.xml
// is built from the identical ranked query, so one knob (PRERENDER_PART_LIMIT)
// moves both surfaces and no advertised URL serves the bare shell.
//
// The route data comes from seo-manifest.json, a snapshot committed alongside
// the code because the frontend build stage has no network and no database.
// Regenerate it with `node scripts/gen-seo-manifest.mjs` whenever the category
// taxonomy or its descriptions change. A missing manifest degrades to the
// static routes only; it never fails the build.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';
import {
  SITE_ORIGIN,
  homeSeo,
  type PageSeo,
  type SeoLink,
} from '../src/public/services/seo';
import { STATIC_PAGE_SEO, categorySeo, partSeo } from '../src/public/services/seoRoutes';
import { categoryPath } from '../src/shared/utils/categoryPath';

interface ManifestCategory {
  slug: string;
  name: string;
  description?: string | null;
  children?: {
    slug: string;
    name: string;
    description?: string | null;
    /** Page-1 part links, rendered into this subcategory's noscript body. */
    parts?: SeoLink[];
  }[];
}

interface ManifestPart {
  slug: string;
  sku: string;
  manufacturerName?: string | null;
  description?: string | null;
  categoryName?: string | null;
  categorySlug?: string | null;
  parentCategorySlug?: string | null;
  bestPrice?: number | null;
}

interface SeoManifest {
  categories?: ManifestCategory[];
  parts?: ManifestPart[];
}

interface PrerenderRoute {
  /** Root-relative URL. */
  urlPath: string;
  /** Output file, relative to dist/. */
  file: string;
  seo: PageSeo;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// A JSON-LD payload is injected as raw script content, so a literal "</script>"
// anywhere inside a description would close the block early. Escaping the
// opening angle bracket is valid JSON and valid JavaScript, and keeps the
// payload byte-identical to what JSON.parse sees.
function escapeJsonLd(json: string): string {
  return json.replace(/</g, '\\u003c');
}

// Every replacement below asserts it matched. The shell is generated by Vite
// from index.html; if that file's shape changes (a tag reworded, an attribute
// reordered) a silent no-op here would ship 97 pages carrying the generic head
// again, which is exactly the defect this step exists to fix. Failing the build
// is the only way that stays visible.
function replaceOnce(html: string, pattern: RegExp, replacement: string, what: string): string {
  if (!pattern.test(html)) {
    throw new Error(
      `[seo-prerender] could not find ${what} in dist/index.html — the shell ` +
        `changed and the prerendered head would be wrong. Update scripts/seoPrerender.ts.`,
    );
  }
  return html.replace(pattern, () => replacement);
}

// Every tag <PageHead> also renders is marked, because helmet on React 19
// appends its copy instead of replacing ours. @shared/seoPrerenderHandoff
// removes the marked tags on boot so a JS client ends up with exactly one of
// each; a crawler that runs no JS keeps them. og:*/twitter:* are deliberately
// NOT marked — helmet renders no counterpart, so they have to survive.
const MARK = 'data-seo-prerendered';

function headTags(seo: PageSeo): string {
  const tags: string[] = [];
  if (seo.canonical) {
    tags.push(`<link ${MARK} rel="canonical" href="${escapeHtml(seo.canonical)}"/>`);
  }
  if (seo.robots) {
    tags.push(`<meta ${MARK} name="robots" content="${escapeHtml(seo.robots)}"/>`);
  }
  for (const json of seo.jsonLd) {
    tags.push(`<script ${MARK} type="application/ld+json">${escapeJsonLd(json)}</script>`);
  }
  return tags.join('\n    ');
}

function noscriptBody(seo: PageSeo): string {
  const links = seo.links
    .map((l: SeoLink) => `<li><a href="${escapeHtml(l.href)}">${escapeHtml(l.label)}</a></li>`)
    .join('');
  return (
    `<noscript><h1>${escapeHtml(seo.heading)}</h1>` +
    `<p>${escapeHtml(seo.description)}</p>` +
    (links ? `<ul>${links}</ul>` : '') +
    `</noscript>`
  );
}

function renderRoute(shell: string, route: PrerenderRoute): string {
  const { seo } = route;
  let html = shell;
  html = replaceOnce(html, /<title>[\s\S]*?<\/title>/, `<title>${escapeHtml(seo.title)}</title>`, '<title>');
  html = replaceOnce(
    html,
    /<meta name="description" content="[\s\S]*?"\s*\/>/,
    `<meta ${MARK} name="description" content="${escapeHtml(seo.description)}"/>`,
    'the description meta',
  );
  html = replaceOnce(
    html,
    /<meta property="og:title" content="[\s\S]*?"\s*\/>/,
    `<meta property="og:title" content="${escapeHtml(seo.title)}"/>`,
    'the og:title meta',
  );
  html = replaceOnce(
    html,
    /<meta property="og:description" content="[\s\S]*?"\s*\/>/,
    `<meta property="og:description" content="${escapeHtml(seo.description)}"/>`,
    'the og:description meta',
  );
  html = replaceOnce(
    html,
    /<meta name="twitter:title" content="[\s\S]*?"\s*\/>/,
    `<meta name="twitter:title" content="${escapeHtml(seo.title)}"/>`,
    'the twitter:title meta',
  );
  html = replaceOnce(
    html,
    /<meta name="twitter:description" content="[\s\S]*?"\s*\/>/,
    `<meta name="twitter:description" content="${escapeHtml(seo.description)}"/>`,
    'the twitter:description meta',
  );
  // og:url tracks the served URL even where canonical is absent (/search),
  // otherwise every non-canonical route would share the home page's preview.
  html = replaceOnce(
    html,
    /<meta property="og:url" content="[\s\S]*?"\s*\/>/,
    `<meta property="og:url" content="${escapeHtml(seo.canonical ?? SITE_ORIGIN + route.urlPath)}"/>`,
    'the og:url meta',
  );
  html = replaceOnce(html, /<\/head>/, `  ${headTags(seo)}\n  </head>`, '</head>');
  html = replaceOnce(
    html,
    /<div id="root"><\/div>/,
    `<div id="root">${noscriptBody(seo)}</div>`,
    'the empty #root div',
  );
  return html;
}

function readManifest(manifestPath: string): SeoManifest | null {
  if (!existsSync(manifestPath)) return null;
  try {
    return JSON.parse(readFileSync(manifestPath, 'utf8')) as SeoManifest;
  } catch {
    return null;
  }
}

function buildRoutes(manifest: SeoManifest | null): PrerenderRoute[] {
  const categories = manifest?.categories ?? [];
  const topLevelLinks: SeoLink[] = categories.map((c) => ({
    href: `/category/${c.slug}`,
    label: c.name,
  }));

  // Home is written to home.html, NOT index.html. index.html stays the generic
  // SPA fallback for every route this step does not cover (part pages, keyword
  // profiles, 404s); baking home's canonical into it would make all 3,600 part
  // URLs declare `rel=canonical -> /`. nginx maps `location = /` to home.html.
  const routes: PrerenderRoute[] = [
    { urlPath: '/', file: 'home.html', seo: homeSeo(topLevelLinks) },
    { urlPath: '/about', file: 'about/index.html', seo: STATIC_PAGE_SEO.about },
    { urlPath: '/contact', file: 'contact/index.html', seo: STATIC_PAGE_SEO.contact },
    // No '/pricing' entry: that route merged into /join on 2026-08-14 and now
    // client-redirects there. Prerendering a document for it would serve a
    // self-canonical page for a URL whose content lives somewhere else.
    { urlPath: '/join', file: 'join/index.html', seo: STATIC_PAGE_SEO.join },
    { urlPath: '/bom', file: 'bom/index.html', seo: STATIC_PAGE_SEO.bom },
    { urlPath: '/keyword', file: 'keyword/index.html', seo: STATIC_PAGE_SEO.keyword },
    { urlPath: '/privacy', file: 'privacy/index.html', seo: STATIC_PAGE_SEO.privacy },
    // /terms shared the privacy canonical while it rendered the privacy
    // component. It is its own document now, so it gets its own head — leaving
    // the old alias would have every terms URL declare itself a duplicate of
    // /privacy and drop out of the index.
    { urlPath: '/terms', file: 'terms/index.html', seo: STATIC_PAGE_SEO.terms },
    {
      urlPath: '/acceptable-use',
      file: 'acceptable-use/index.html',
      seo: STATIC_PAGE_SEO.acceptableUse,
    },
    { urlPath: '/search', file: 'search/index.html', seo: STATIC_PAGE_SEO.search },
  ];

  for (const category of categories) {
    const children = category.children ?? [];
    routes.push({
      urlPath: `/category/${category.slug}`,
      file: `category/${category.slug}/index.html`,
      seo: categorySeo({
        name: category.name,
        canonicalPath: `/category/${category.slug}`,
        description: category.description ?? null,
        children: children.map((c) => ({
          href: `/category/${category.slug}/${c.slug}`,
          label: c.name,
        })),
      }),
    });
    for (const child of children) {
      const seo = categorySeo({
        name: child.name,
        canonicalPath: `/category/${category.slug}/${child.slug}`,
        description: child.description ?? null,
        parent: { name: category.name, slug: category.slug },
      });
      routes.push({
        urlPath: `/category/${category.slug}/${child.slug}`,
        file: `category/${category.slug}/${child.slug}/index.html`,
        // The subcategory's own parts, APPENDED after the breadcrumb links
        // categorySeo built. Without them the prerendered document links only
        // upward, and every part page below it is a crawl orphan reachable
        // solely through the sitemap — a discovered URL with nothing linking
        // to it carries no internal signal at all. This is the one place the
        // home -> category -> subcategory -> part path exists in raw HTML.
        //
        // Appended here rather than passed as categorySeo's `children`: that
        // field means subcategories, and the runtime <PageHead> on the live
        // category page has no part list to pass, so a builder argument would
        // have to be one the two consumers disagree about. links only feed the
        // noscript body, which the prerender alone emits.
        seo: { ...seo, links: [...seo.links, ...(child.parts ?? [])] },
      });
    }
  }

  // Already capped and ranked by the manifest generator — this loop writes
  // whatever it is given and does no selection of its own, so the policy has
  // exactly one home. Only parts WITH a slug are here (the manifest drops the
  // rest), since /part/<uuid> canonicalizes to the slug form anyway —
  // prerendering both shapes would emit two documents that disagree about
  // which is canonical.
  for (const part of manifest?.parts ?? []) {
    routes.push({
      urlPath: `/part/${part.slug}`,
      file: `part/${part.slug}/index.html`,
      seo: partSeo({
        sku: part.sku,
        manufacturerName: part.manufacturerName ?? '',
        slug: part.slug,
        description: part.description ?? null,
        categoryName: part.categoryName ?? null,
        bestPrice: part.bestPrice ?? null,
        categoryPath: part.categorySlug
          ? categoryPath(part.categorySlug, part.parentCategorySlug ?? null)
          : null,
      }),
    });
  }

  return routes;
}

export function seoPrerender(options: { manifestPath: string; outDir: string }): Plugin {
  return {
    name: 'circuits-seo-prerender',
    apply: 'build',
    // closeBundle, not writeBundle: dist/index.html must already be on disk,
    // and the PWA plugin precaches nothing (globPatterns: []) so ordering
    // against it does not matter.
    closeBundle: {
      sequential: true,
      order: 'post',
      handler() {
        const outDir = options.outDir;
        const shellPath = path.join(outDir, 'index.html');
        if (!existsSync(shellPath)) return;

        const shell = readFileSync(shellPath, 'utf8');
        const manifest = readManifest(options.manifestPath);
        if (!manifest) {
          this.warn(
            `[seo-prerender] ${path.basename(options.manifestPath)} missing or unreadable — ` +
              `category routes will fall back to the generic shell. ` +
              `Run \`node scripts/gen-seo-manifest.mjs\` against a running API.`,
          );
        }

        const routes = buildRoutes(manifest);
        for (const route of routes) {
          const dest = path.join(outDir, route.file);
          mkdirSync(path.dirname(dest), { recursive: true });
          writeFileSync(dest, renderRoute(shell, route), 'utf8');
        }
        // Broken down by type because the part count is the one that can
        // silently collapse: a manifest regenerated against an API without
        // the capped-slice endpoint would still emit a plausible-looking
        // total made entirely of categories.
        const parts = routes.filter((r) => r.urlPath.startsWith('/part/')).length;
        const categories = routes.filter((r) => r.urlPath.startsWith('/category/')).length;
        this.info(
          `[seo-prerender] wrote ${routes.length} indexable HTML documents ` +
            `(${routes.length - parts - categories} static, ${categories} category, ${parts} part)`,
        );
      },
    },
  };
}
