// Build-time SEO prerender — the reason circuitcenter.ai serves indexable HTML.
//
// The site is a client-rendered SPA behind nginx with no Node in the request
// path, so every URL used to resolve to one byte-identical index.html: same
// <title>, same meta description, no canonical, no JSON-LD. This step writes
// ONE static HTML file per templated route, each carrying that route's own head
// (built by @public/services/seo, the same module <PageHead> renders from) plus
// a <noscript> body for crawlers that do not execute JS. nginx then serves them
// with the try_files rule already in frontend/nginx.conf — no runtime cost, no
// extra request-path service, and not one byte added to the JS bundle.
//
// Scope is deliberately bounded to the 97 templated routes (home, the static
// pages, 15 categories, 75 subcategories). Part pages are NOT prerendered — see
// the note in vite.config.ts for why.
//
// The route data comes from seo-manifest.json, a snapshot committed alongside
// the code because the frontend build stage has no network and no database.
// Regenerate it with `node scripts/gen-seo-manifest.mjs` whenever the category
// taxonomy or its descriptions change. A missing manifest degrades to the
// static routes only; it never fails the build.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';
import {
  SITE_ORIGIN,
  STATIC_PAGE_SEO,
  categorySeo,
  homeSeo,
  type PageSeo,
  type SeoLink,
} from '../src/public/services/seo';

interface ManifestCategory {
  slug: string;
  name: string;
  description?: string | null;
  children?: { slug: string; name: string; description?: string | null }[];
}

interface SeoManifest {
  categories?: ManifestCategory[];
}

interface PrerenderRoute {
  /** Root-relative URL. */
  urlPath: string;
  /** Output file, relative to dist/. */
  file: string;
  seo: PageSeo;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// A JSON-LD payload is injected as raw script content, so a literal "</script>"
// anywhere inside a description would close the block early. Escaping the
// opening angle bracket is valid JSON and valid JavaScript, and keeps the
// payload byte-identical to what JSON.parse sees.
function escapeJsonLd(json: string): string {
  return json.replace(/</g, '\\u003c');
}

// Every replacement below asserts it matched. The shell is generated by Vite
// from index.html; if that file's shape changes (a tag reworded, an attribute
// reordered) a silent no-op here would ship 97 pages carrying the generic head
// again, which is exactly the defect this step exists to fix. Failing the build
// is the only way that stays visible.
function replaceOnce(html: string, pattern: RegExp, replacement: string, what: string): string {
  if (!pattern.test(html)) {
    throw new Error(
      `[seo-prerender] could not find ${what} in dist/index.html — the shell ` +
        `changed and the prerendered head would be wrong. Update scripts/seoPrerender.ts.`,
    );
  }
  return html.replace(pattern, () => replacement);
}

// Every tag <PageHead> also renders is marked, because helmet on React 19
// appends its copy instead of replacing ours. @shared/seoPrerenderHandoff
// removes the marked tags on boot so a JS client ends up with exactly one of
// each; a crawler that runs no JS keeps them. og:*/twitter:* are deliberately
// NOT marked — helmet renders no counterpart, so they have to survive.
const MARK = 'data-seo-prerendered';

function headTags(seo: PageSeo): string {
  const tags: string[] = [];
  if (seo.canonical) {
    tags.push(`<link ${MARK} rel="canonical" href="${escapeHtml(seo.canonical)}"/>`);
  }
  if (seo.robots) {
    tags.push(`<meta ${MARK} name="robots" content="${escapeHtml(seo.robots)}"/>`);
  }
  for (const json of seo.jsonLd) {
    tags.push(`<script ${MARK} type="application/ld+json">${escapeJsonLd(json)}</script>`);
  }
  return tags.join('\n    ');
}

function noscriptBody(seo: PageSeo): string {
  const links = seo.links
    .map((l: SeoLink) => `<li><a href="${escapeHtml(l.href)}">${escapeHtml(l.label)}</a></li>`)
    .join('');
  return (
    `<noscript><h1>${escapeHtml(seo.heading)}</h1>` +
    `<p>${escapeHtml(seo.description)}</p>` +
    (links ? `<ul>${links}</ul>` : '') +
    `</noscript>`
  );
}

function renderRoute(shell: string, route: PrerenderRoute): string {
  const { seo } = route;
  let html = shell;
  html = replaceOnce(html, /<title>[\s\S]*?<\/title>/, `<title>${escapeHtml(seo.title)}</title>`, '<title>');
  html = replaceOnce(
    html,
    /<meta name="description" content="[\s\S]*?"\s*\/>/,
    `<meta ${MARK} name="description" content="${escapeHtml(seo.description)}"/>`,
    'the description meta',
  );
  html = replaceOnce(
    html,
    /<meta property="og:title" content="[\s\S]*?"\s*\/>/,
    `<meta property="og:title" content="${escapeHtml(seo.title)}"/>`,
    'the og:title meta',
  );
  html = replaceOnce(
    html,
    /<meta property="og:description" content="[\s\S]*?"\s*\/>/,
    `<meta property="og:description" content="${escapeHtml(seo.description)}"/>`,
    'the og:description meta',
  );
  html = replaceOnce(
    html,
    /<meta name="twitter:title" content="[\s\S]*?"\s*\/>/,
    `<meta name="twitter:title" content="${escapeHtml(seo.title)}"/>`,
    'the twitter:title meta',
  );
  html = replaceOnce(
    html,
    /<meta name="twitter:description" content="[\s\S]*?"\s*\/>/,
    `<meta name="twitter:description" content="${escapeHtml(seo.description)}"/>`,
    'the twitter:description meta',
  );
  // og:url tracks the served URL even where canonical is absent (/search),
  // otherwise every non-canonical route would share the home page's preview.
  html = replaceOnce(
    html,
    /<meta property="og:url" content="[\s\S]*?"\s*\/>/,
    `<meta property="og:url" content="${escapeHtml(seo.canonical ?? SITE_ORIGIN + route.urlPath)}"/>`,
    'the og:url meta',
  );
  html = replaceOnce(html, /<\/head>/, `  ${headTags(seo)}\n  </head>`, '</head>');
  html = replaceOnce(
    html,
    /<div id="root"><\/div>/,
    `<div id="root">${noscriptBody(seo)}</div>`,
    'the empty #root div',
  );
  return html;
}

function readManifest(manifestPath: string): SeoManifest | null {
  if (!existsSync(manifestPath)) return null;
  try {
    return JSON.parse(readFileSync(manifestPath, 'utf8')) as SeoManifest;
  } catch {
    return null;
  }
}

function buildRoutes(manifest: SeoManifest | null): PrerenderRoute[] {
  const categories = manifest?.categories ?? [];
  const topLevelLinks: SeoLink[] = categories.map((c) => ({
    href: `/category/${c.slug}`,
    label: c.name,
  }));

  // Home is written to home.html, NOT index.html. index.html stays the generic
  // SPA fallback for every route this step does not cover (part pages, keyword
  // profiles, 404s); baking home's canonical into it would make all 3,600 part
  // URLs declare `rel=canonical -> /`. nginx maps `location = /` to home.html.
  const routes: PrerenderRoute[] = [
    { urlPath: '/', file: 'home.html', seo: homeSeo(topLevelLinks) },
    { urlPath: '/about', file: 'about/index.html', seo: STATIC_PAGE_SEO.about },
    { urlPath: '/contact', file: 'contact/index.html', seo: STATIC_PAGE_SEO.contact },
    { urlPath: '/join', file: 'join/index.html', seo: STATIC_PAGE_SEO.join },
    { urlPath: '/keyword', file: 'keyword/index.html', seo: STATIC_PAGE_SEO.keyword },
    { urlPath: '/privacy', file: 'privacy/index.html', seo: STATIC_PAGE_SEO.privacy },
    // /terms renders the privacy component and shares its canonical — one page,
    // two URLs, and the raw HTML has to say so.
    { urlPath: '/terms', file: 'terms/index.html', seo: STATIC_PAGE_SEO.privacy },
    { urlPath: '/search', file: 'search/index.html', seo: STATIC_PAGE_SEO.search },
  ];

  for (const category of categories) {
    const children = category.children ?? [];
    routes.push({
      urlPath: `/category/${category.slug}`,
      file: `category/${category.slug}/index.html`,
      seo: categorySeo({
        name: category.name,
        canonicalPath: `/category/${category.slug}`,
        description: category.description ?? null,
        children: children.map((c) => ({
          href: `/category/${category.slug}/${c.slug}`,
          label: c.name,
        })),
      }),
    });
    for (const child of children) {
      routes.push({
        urlPath: `/category/${category.slug}/${child.slug}`,
        file: `category/${category.slug}/${child.slug}/index.html`,
        seo: categorySeo({
          name: child.name,
          canonicalPath: `/category/${category.slug}/${child.slug}`,
          description: child.description ?? null,
          parent: { name: category.name, slug: category.slug },
        }),
      });
    }
  }

  return routes;
}

export function seoPrerender(options: { manifestPath: string; outDir: string }): Plugin {
  return {
    name: 'circuits-seo-prerender',
    apply: 'build',
    // closeBundle, not writeBundle: dist/index.html must already be on disk,
    // and the PWA plugin precaches nothing (globPatterns: []) so ordering
    // against it does not matter.
    closeBundle: {
      sequential: true,
      order: 'post',
      handler() {
        const outDir = options.outDir;
        const shellPath = path.join(outDir, 'index.html');
        if (!existsSync(shellPath)) return;

        const shell = readFileSync(shellPath, 'utf8');
        const manifest = readManifest(options.manifestPath);
        if (!manifest) {
          this.warn(
            `[seo-prerender] ${path.basename(options.manifestPath)} missing or unreadable — ` +
              `category routes will fall back to the generic shell. ` +
              `Run \`node scripts/gen-seo-manifest.mjs\` against a running API.`,
          );
        }

        const routes = buildRoutes(manifest);
        for (const route of routes) {
          const dest = path.join(outDir, route.file);
          mkdirSync(path.dirname(dest), { recursive: true });
          writeFileSync(dest, renderRoute(shell, route), 'utf8');
        }
        this.info(`[seo-prerender] wrote ${routes.length} indexable HTML documents`);
      },
    },
  };
}
