upstream frontend {
    server frontend:80;
}

upstream api {
    server api:8000;
}

server {
    listen 80;
    server_name circuits.matthew-chirichella.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name circuits.matthew-chirichella.com;

    ssl_certificate /etc/letsencrypt/live/circuits.matthew-chirichella.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/circuits.matthew-chirichella.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /api/ {
        proxy_pass http://api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect http:// https://;
    }

    location /admin {
        proxy_pass http://api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect http:// https://;
    }

    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
