// The vendored KiCanvas bundle (frontend/vendor/build/kicanvas.js, generated by
// scripts/build-kicanvas.mjs). Importing it registers the <kicanvas-embed> and
// <kicanvas-source> custom elements; it exports nothing the site calls — every
// interaction goes through kicanvasController.ts and DOM queries.
declare module '@vendor-build/kicanvas' {}
