// The REAL (country, region) pairs the production database has recorded, as
// of 2026-08-30 — 144 of them across 52 countries, taken straight out of
// `page_views` (`GROUP BY country, region`).
//
// This is a FIXTURE, not a sample: regionJoin.test.ts runs the shipped join
// over every one of them against the committed Natural Earth assets and pins
// both the coverage number and the exact list of names that still find no
// polygon. That is the only honest way to state coverage — the alternative is
// a claim about invented names, which the join would always pass.
//
// Regenerate after a long stretch of new traffic:
//   docker compose exec -T db psql -U circuits -d circuits -At -F'|' -c \
//     "SELECT country, region, count(*) FROM page_views \
//      WHERE country IS NOT NULL AND region IS NOT NULL \
//      GROUP BY 1,2 ORDER BY 1, 3 DESC;"

/** ISO alpha-2 -> [subdivision name as DB-IP wrote it, page views]. */
export const OBSERVED_REGIONS: Record<string, Array<[string, number]>> = {
  AF: [['Kabul', 4]],
  AR: [['Buenos Aires', 4]],
  AU: [['New South Wales', 3], ['Victoria', 1]],
  BD: [['Dhaka Division', 2]],
  BE: [['Wallonia', 2]],
  BR: [
    ['São Paulo', 6],
    ['Espírito Santo', 1],
    ['Piauí', 1],
    ['Santa Catarina', 1],
    ['Rio Grande do Sul', 1],
    ['Pernambuco', 1],
    ['Rio de Janeiro', 1],
  ],
  BY: [['Minsk City', 3]],
  CA: [
    ['British Columbia', 9],
    ['Ontario', 6],
    ['Quebec', 3],
    ['Alberta', 2],
    ['Nova Scotia', 2],
    ['Manitoba', 1],
    ['Saskatchewan', 1],
  ],
  CG: [['Brazzaville', 7]],
  CI: [['Abidjan Autonomous District', 1]],
  CN: [
    ['Guangdong', 20],
    ['Jiangsu', 9],
    ['Beijing', 6],
    ['Sichuan', 4],
    ['Fujian', 2],
    ['Henan', 1],
    ['Zhejiang', 1],
  ],
  DE: [['Hesse', 10], ['Bavaria', 7], ['Saxony', 6], ['State of Berlin', 2]],
  EG: [['Giza', 18], ['Dakahlia', 3], ['Cairo', 2], ['Alexandria', 1]],
  ES: [['Valencia', 16]],
  FI: [['Uusimaa', 6]],
  FR: [
    ['Île-de-France', 5],
    ['Hauts-de-France', 4],
    ['Provence-Alpes-Côte d\'Azur', 1],
    ['Rhône-Alpes', 1],
  ],
  GB: [['England', 19], ['Scotland', 2], ['Wales', 1]],
  GH: [['Greater Accra', 4]],
  GT: [['Izabal', 1]],
  HK: [['Kowloon', 2], ['Kwai Tsing District', 1]],
  ID: [['West Java', 1]],
  IE: [['Leinster', 7]],
  IL: [['Central District', 2], ['Jerusalem', 1], ['Haifa', 1]],
  IN: [
    ['Karnataka', 20],
    ['Punjab', 15],
    ['Maharashtra', 13],
    ['Telangana', 9],
    ['Tamil Nadu', 8],
    ['Madhya Pradesh', 7],
    ['Haryana', 6],
    ['Uttar Pradesh', 1],
    ['Andhra Pradesh', 1],
    ['Gujarat', 1],
  ],
  IT: [['Friuli Venezia Giulia', 8], ['Lazio', 4], ['Campania', 1]],
  JO: [['Balqa', 4], ['Amman', 1]],
  JP: [['Kanagawa', 2], ['Tokyo', 2]],
  KE: [['Nairobi County', 6]],
  KR: [['Gyeonggi-do', 1]],
  LK: [['Western Province', 3], ['Western', 3], ['Central Province', 1]],
  LT: [['Siauliai', 1]],
  LV: [['Riga', 1]],
  MG: [['Analamanga', 5]],
  MM: [['Yangon', 1]],
  NG: [
    ['Oyo State', 5],
    ['Lagos', 4],
    ['Kano State', 4],
    ['FCT', 1],
    ['Adamawa', 1],
    ['Yobe State', 1],
  ],
  NL: [['North Holland', 10], ['Groningen', 4], ['Friesland', 2]],
  NO: [['Østfold', 11], ['Troms', 1]],
  PH: [['Mimaropa', 2], ['Bicol Region', 2], ['National Capital Region', 1]],
  PL: [['Mazovia', 3]],
  RO: [['Bucharest', 1]],
  RU: [['Moscow', 8]],
  SE: [['Västerbotten', 8], ['Norrbotten', 2], ['Stockholm', 2]],
  TH: [['Bangkok', 3], ['Chiang Mai', 1]],
  TM: [['Ashgabat', 1]],
  TR: [['Sivas', 6], ['Ankara', 3], ['Istanbul', 2]],
  TW: [['Taiwan', 2]],
  US: [
    ['Washington', 3713],
    ['New York', 3630],
    ['Virginia', 349],
    ['Vermont', 230],
    ['California', 94],
    ['Iowa', 55],
    ['Oregon', 55],
    ['Michigan', 31],
    ['New Jersey', 29],
    ['Texas', 21],
    ['North Carolina', 21],
    ['Florida', 14],
    ['District of Columbia', 10],
    ['Maryland', 9],
    ['Georgia', 9],
    ['Massachusetts', 9],
    ['Arizona', 8],
    ['South Carolina', 7],
    ['Kentucky', 4],
    ['Illinois', 4],
    ['Alabama', 4],
    ['Pennsylvania', 2],
    ['Hawaii', 1],
    ['Nevada', 1],
    ['Missouri', 1],
    ['Connecticut', 1],
    ['Colorado', 1],
    ['Oklahoma', 1],
    ['Ohio', 1],
  ],
  UZ: [['Tashkent', 6]],
  VE: [['Miranda', 1]],
  VN: [['Hanoi', 5], ['Hai Phong', 1]],
  ZA: [['Gauteng', 1]],
  ZW: [['Harare', 2]],
};
