<?php
/**
 * GENERATED by mail/make-signature-assets.py -- do not edit.
 *
 * Every social mark that exists on disk. signature-roster.php feeds this
 * to the company block as 'icon_slugs', and sig_social_row will only emit
 * an <img> for a slug in here; everything else renders as a text link.
 *
 * The template cannot check this itself. It builds a URL on a different
 * host, so it has no file to stat, and it must stay a pure function.
 * Guarded by test_template.php, which asserts this list equals the
 * social-*.png files actually present.
 */
return [
    'behance',
    'bitbucket',
    'bluesky',
    'buymeacoffee',
    'calendly',
    'crunchbase',
    'devto',
    'discord',
    'discourse',
    'dribbble',
    'etsy',
    'facebook',
    'figma',
    'github',
    'gitlab',
    'goodreads',
    'hashnode',
    'huggingface',
    'instagram',
    'kaggle',
    'kofi',
    'linkedin',
    'mastodon',
    'matrix',
    'medium',
    'notion',
    'orcid',
    'patreon',
    'pinterest',
    'producthunt',
    'reddit',
    'researchgate',
    'shopify',
    'signal',
    'snapchat',
    'soundcloud',
    'spotify',
    'stackoverflow',
    'steam',
    'strava',
    'substack',
    'telegram',
    'threads',
    'tiktok',
    'twitch',
    'vimeo',
    'whatsapp',
    'x',
    'xing',
    'youtube',
    'zoom',
];
